import Head from "next/head";
import Image from "next/image";
import { CardSkill, Container, ContainerBlog, ContainerSkills, Footer, Header, Main, PictureContainer, Presentation, ProfilePicture, Wrapper } from "./styles";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        site
      </Header>
      <Main>
        <PictureContainer>
          <ProfilePicture>
            <img src="fotosemfundo3.png"/>
          </ProfilePicture>
        </PictureContainer>
        <Presentation>
          <Wrapper>
            <h3>Welcome I'm</h3>
            <h1>Luiz Fernando</h1>
            <h3>web developer</h3>
            <p>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolore,
              ut atque delectus dolorum illo numquam odio, obcaecati est
              blanditiis laudantium sint voluptatum, nihil voluptate nisi ab
              pariatur. Vero, similique in.
            </p>
          </Wrapper>
        </Presentation>
      </Main>
      <ContainerSkills>
        <CardSkill/>
        <CardSkill/>
        <CardSkill/>
        <CardSkill/>
      </ContainerSkills>
      <ContainerBlog></ContainerBlog>
      <Footer>LUIZ FERNANDO</Footer>
    </Container>
  );
}